apiVersion: v1
kind: ConfigMap
metadata:
  name: common-data-configmap
  namespace: ecommerce-project
data:
  PORT: "9000"
  ACTIVE_PROFILE: "dev"
  DB_HOST: "mysql-service"
  DB_PORT: "3306"
  DB_SCHEMA: "ecommerce_app_database"
  DB_USER: "mysqluser"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"