apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: ecommerce-project
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "mypass"
  MYSQL_DATABASE: "ecommerce_app_database"
  MYSQL_USER: "mysqluser"
  MYSQL_PASSWORD: "mypass"