apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: ecommerce-project
spec:
  selector:
    app: payment
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9050
      targetPort: 9050