apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: ecommerce-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: authentication-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7000
          envFrom:
            - configMapRef:
                name: auth-configmap
            - secretRef:
                name: auth-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"