# Stage 1 : Build React app
FROM node:14-alpine AS builder

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install

COPY . .

RUN yarn build

# Stage 2 : Runtime
FROM node:14-alpine

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install --production

COPY --from=builder /app/build ./build
COPY server.js ./server.js

ENV PORT=3000

EXPOSE 3000

CMD ["node", "server.js"]