server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /api/data/ {
        proxy_pass http://common-data-service:9000/;
        proxy_set_header Host $host;
    }

    location /api/auth/ {
        proxy_pass http://auth-service:7000/;
        proxy_set_header Host $host;
    }


}